#!/usr/bin/env node
/**
 * i18n-status — emits docs/i18n/STATUS.md table per blog slug & locale.
 */
import { readdirSync, existsSync, writeFileSync, readFileSync as rfs } from "node:fs";
import { join } from "node:path";
const ROOT = join(import.meta.dirname, "..");
const LOCALES = ["zh", "pt-br", "ru", "ja", "tr", "ko"];
const enDir = join(ROOT, "apps/web/src/content/blog/en");
const enSlugs = existsSync(enDir) ? readdirSync(enDir).filter(f => f.endsWith(".md")).map(f => f.replace(/\.md$/, "")) : [];
let md = `# i18n Translation Status\n\nAuto-generated by \`scripts/i18n-status.mjs\`. Do not edit manually.\n\n`;
md += `Source: \`apps/web/src/content/blog/en\` — ${enSlugs.length} posts\n\n`;
md += `| Slug | ${LOCALES.join(" | ")} |\n`;
md += `|------|${LOCALES.map(() => "---").join("|")}|\n`;
for (const slug of enSlugs) {
  const cells = LOCALES.map(loc => {
    const p = join(ROOT, `apps/web/src/content/blog/${loc}/${slug}.md`);
    if (!existsSync(p)) return "⬜ missing";
    const c = rfs(p, "utf-8");
    if (c.includes("draft: true") || c.includes("needsReview: true")) return "📝 draft";
    return "✅ present";
  });
  md += `| ${slug} | ${cells.join(" | ")} |\n`;
}
md += `\nLegend: ✅ present · 📝 draft/MT needs review · ⬜ missing (fallback to EN)\n`;
const out = join(ROOT, "docs/i18n/STATUS.md");
writeFileSync(out, md, "utf-8");
console.log(`wrote ${out}`);
